### PR TITLE
(feat) : Add support for tables, images, and horizontal rules

### LINKED ISSUE #1: [Feat] : Extend support for additional markdown features: tables, images, horizontal rules
### Enhancement Request

Currently, the markdown-to-HTML converter supports basic markdown syntax. However, it lacks support for additional features such as tables, images, and comprehensive horizontal rule detection. To improve the utility of the package, I propose extending support for these markdown features.

### Proposed Changes
- **Tables**: Convert markdown table syntax into HTML table elements.
- **Images**: Convert markdown image syntax into HTML image elements.
- **Horizontal Rules**: Improve support for different types of horizontal rules (---, ***, ___).

These enhancements will make the package more robust and versatile, allowing users to convert a broader range of markdown syntax into HTML.

### PR DESCRIPTION
**Pull request by JasrajChouhan**
fixes : #1 

### Overview

This pull request introduces support for additional markdown features to the markdown-to-HTML converter. The following features have been added:

- **Tables**: Markdown tables are now converted to HTML tables using the correct syntax.
- **Images**: Markdown images are converted into HTML img tags with appropriate attributes.
- **Horizontal Rules**: Enhanced support for detecting horizontal rules written in different styles (---, ***, ___).

### Changes Made
- Added regex pattern to detect and convert markdown tables into `<table>` and `<td>` elements.
- Implemented image conversion by detecting the `alt` pattern and converting it to an `` tag.
- Improved the detection of horizontal rules to cover different markdown styles.

### Testing
All new features have been tested with various markdown inputs to ensure accurate conversion and correct HTML output.

### Related Issue
fixes: #1 

### Additional Information
These enhancements will make the package more versatile and capable of handling a broader range of markdown syntax, improving its utility for developers.

### CODE REVIEW

**Comment by Webb-orbit** [comment]
oh yes i work now this functionality's it's take some time 
Images, Horizontal line are done!  but i stuck  creating table
you can help me?

**Comment by JasrajChouhan** [comment]
yes

**Comment by Webb-orbit** [comment]
thanks your table regex is helpful for me

**Comment by Webb-orbit** [comment]
close

**Pull request closed without merging**
